- name: JavaScript
  logo: javascript
  url: https://github.com/Matt-Gleich?tab=repositories&q=&type=&language=javascript
  color: F1E05A
  projects:
    - https://github.com/Matt-Gleich/components
    - https://github.com/Matt-Gleich/React-Translator
    - https://github.com/Matt-Gleich/Extreme-Fib-Calc
- name: TypeScript
  logo: typescript
  url: https://www.typescriptlang.org
  color: 007ACC
  projects:
    - url: https://github.com/Matt-Gleich/emoji-clock
      wip: true
